#!/bin/sh

if [ -x "$(command -v exa)" ]; then
    alias ls='exa -h'
    alias la='exa -ah --color=always --group-directories-first'
    alias ll='exa -lh --color=always --group-directories-first --time-style=long-iso '
    alias lal='exa -alh --color=always --group-directories-first --time-style=long-iso '
    alias lalt='exa -alh --color=always --group-directories-first --time-style=long-iso --modified'
else
    export TIME_STYLE=long-iso
    alias la='ls -a'
    alias ll='ls -lh'
    alias lal='ls -alh'
    alias lalt='ls -alht'
fi

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

alias dotf=${MYDOTFILES}

alias lzg='lazygit'
alias fugi='nvim +G' # Open nvim with vim-fugitive
alias flg='nvim +Flog' # Open nvim with Flog

alias xo='xdg-open'

## SYSTEM SPECIFIC ALIASES BELOW: ##
alias qstatu='qstat -u $USER'
