#!/bin/sh

alias ...='../..'
alias ....='../../..'
alias .....='../../../..'
alias ......='../../../../..'

alias -- -='cd -'
alias 1='cd -'
alias 2='cd -2'
alias 3='cd -3'
alias 4='cd -4'
alias 5='cd -5'
alias 6='cd -6'
alias 7='cd -7'
alias 8='cd -8'
alias 9='cd -9'

alias md='mkdir -p'
alias rd=rmdir

export TIME_STYLE=long-iso
alias la='ls -a --color=tty'
alias la='ls -a --color=auto'
alias ll='ls -lh --color=auto'
alias lal='ls -alh --color=auto'
alias lalt='ls -alht --color=auto'

alias rm='rm -I'
alias cp='cp -i'
alias mv='mv -i'

alias dotf=${MYDOTFILES}

alias lzg='lazygit'
alias fugi='nvim +G' # Open nvim with vim-fugitive
alias flg='nvim +Flog' # Open nvim with Flog

alias xo='xdg-open'

## SYSTEM SPECIFIC ALIASES BELOW: ##
