#!/bin/sh

if [ -x "$(command -v exa)" ]; then
    alias ls='exa'
    alias la='exa -a --color=always --group-directories-first'
    alias ll='exa -l --color=always --group-directories-first'
    alias lal='exa -al --color=always --group-directories-first'
else
    alias la='ls -a'
    alias ll='ls -lh'
    alias lal='ls -alh'
fi

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

alias dotf=${MYDOTFILES}

alias lzg='lazygit'
alias fugi='nvim +G' # Open nvim with vim-fugitive
alias flg='nvim +Flog' # Open nvim with Flog

alias xo='xdg-open'

## SYSTEM SPECIFIC ALIASES BELOW: ##
